apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: easyshop-ingress
  namespace: easyshop-hack 
  annotations: 
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    kubernetes.io/ingress.class: "nginx"
    # Disable SSL redirect for local development
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec: 
  rules: 
  - host: localhost
    http: 
      paths: 
      - path: /
        pathType: Prefix
        backend: 
          service: 
            name: easyshop-service 
            port: 
              number: 80
              