apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: easyshop-hack
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NEXTURL: "http://localhost:3000"
  NEXTAUTH_URL: "http://localhost:3000/api"
