apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: easyshop-hack
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NEXTURL: "https://easyshop-hack.shaheen.homes"
  NEXTAUTH_URL: "https://easyshop-hack.shaheen.homes"
