apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis-deployment
  namespace: easyshop-hack
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: redis 
  template:
    metadata: 
      name: redis-pod
      namespace: easyshop-hack
    spec: 
      containers:
      - name: redis
        image: redis-alpine
        ports: 
        - containerPort: 6379
        resources: 
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "200m"
            livenessProbe: 
            httpGet: 
              exec:
                command:  
                - redis-cli
                - ping
              initialDelaySeconds: 15
              periodSeconds: 20
            readinessProbe:
              exec:
                command:
                - redis-cli
                - ping
              initialDelaySeconds: 5
              periodSeconds: 10
