FROM node:18-slim AS  builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production image
FROM node:18-slim
WORKDIR /app

# Copy built files from builder
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/scripts ./scripts

# Set environment to production
ENV NODE_ENV=production

EXPOSE 3000

# Install ts-node as a dev dependency for running TypeScript files
RUN npm install -g ts-node typescript @types/node

# Set the command to run the migration
CMD ["npx", "ts-node", "scripts/migrate-data.ts"]



